server:  port: 8761spring:  application:    name: microservice-eurekaeureka:  client:    register-with-eureka: false    fetch-registry: false    serviceUrl:      defaultZone: http://localhost:8761/eureka
